

default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: mysite_development 
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost
  port: 5432
  pool: 5

test:
  <<: *default
  database: postgresql

#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  #database: mysite_production
  #username: mysite
  #password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>