default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %> # для локальной работы



development:
  <<: *default
  database: app_blog_development

test:
  <<: *default
  database: app_blog_test

production:
  <<: *default
  database: app_blog_production
  host: db # Прямо указываем имя сервиса из docker-compose