// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
import "./controllers"
import * as bootstrap from "bootstrap"
import "trix"
import  "bootstrap/js/dist/collapse" // Podkluczenie oknaimport "trix"
import "@rails/actiontext"
import "./home"
import "./articles"
import "./devise"
import "./tweets"
import "./custom"